image: nvcr.io/nvidia/pytorch:21.10-py3
port: 8501
command:
  - /bin/sh
  - '-c'
  - |
    cd /opt/repos/repo
    pip install -r requirements.txt
    streamlit run app2.py
models:
  - id: def456
    path: /opt/models
repositories:
  dataset: dsrp37o09pa0h8u
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/joshua-paperspace/ResNet-PyTorch
      name: repo
      ref: main
resources:
  replicas: 1
  instanceType: P5000