# image: joshuapaperspace/resnet18-pytorch
# port: 8000
# env:
#   - name: ENV
#     value: VAR
# resources:
#   replicas: 1
#   instanceType: A100



image: nvcr.io/nvidia/pytorch:21.10-py3
command:
  - echo hello
  - cd /opt/repos/ResNet-PyTorch
  - pip install /opt/repos/ResNet-PyTorch/reqirements.txt
  - python3 app.py
port: 8080
env:
  - name: ENV
    value: VAR
models:
  - id: mosw6t1g2xifi94
    path: /opt/models
repositories:
  dataset: dsrp37o09pa0h8u
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/joshua-paperspace/ResNet-PyTorch
      ref: main
      name: ResNet-PyTorch
resources:
  replicas: 1
  instanceType: P4000


image: nvcr.io/nvidia/pytorch:21.10-py3
command:
  - echo hello
  - cd /opt/repos/ResNet-PyTorch
  - pip install /opt/repos/ResNet-PyTorch/reqirements.txt
  - python3 app.py
port: 8080
env:
  - name: ENV
    value: VAR
models:
  - id: mosw6t1g2xifi94
    path: /opt/models
repositories:
  dataset: dsrp37o09pa0h8u
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/joshua-paperspace/ResNet-PyTorch
      name: ResNet-PyTorch
      ref: main
resources:
  replicas: 1
  instanceType: P4000