defaults:
  env:
    api-key: secret:git_repo_pat
'on':
  github:
    branches:
      only: main
jobs:
  TestSecret:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        echo $api-key
    resources:
      instance-type: C4
