'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  TrainResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        python train_model.py --layers=18 --epochs=1 2>/outputs/path
        cp -R /inputs/repo /outputs
        cp -R /inputs/cifar10 /outputs
        cp -R models /outputs
        echo Trained ResNet18
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      cifar10: 
          type: dataset
          with:
              ref: dsrzkbpudtxoz5q
    outputs:
      models:
        type: dataset
        with:
          ref: dsr7vff9zehs3b3
      cifar10:
        type: dataset
        with:
          ref: dsrzkbpudtxoz5q
      repo:
        type: volume
      path:
        type: string
    resources:
      instance-type: P4000
  TestResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        ls /inputs
        echo hi
        ls /inputs/models
        cp -R /inputs/repo /outputs  
        python test_model.py -m /inputs/models/resnet18-epochs-1.pth
        cp -R test-results /outputs  
    needs:
      - TrainResNet18
    inputs:
      repo: TrainResNet18.outputs.repo
      path: TrainResNet18.outputs.path
      models: TrainResNet18.outputs.models
    outputs:
      test-results:
        type: dataset
        with:
          ref: dstdrdgk1bxsbjs
      repo:
        type: volume
    resources:
      instance-type: P4000
  CompareModels:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        python print_test_results.py
        ls
    needs:
      - TestResNet18
    inputs:
      repo: TestResNet18.outputs.repo
      test-results: TestResNet18.outputs.test-results
    resources:
      instance-type: P5000
context:
  event:
    github:
      url: https://github.com/joshua-paperspace/ResNet-PyTorch

