'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  TrainResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        cp -R /inputs/repo/ /outputs
        cp -R ./hello.json /outputs/json
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      hello:
        type: volume
      repo:
        type: volume
    resources:
      instance-type: C4
  TestResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        ls /inputs
        echo a
        ls /inputs/json
        echo b
        ls /inputs/repo
    needs:
      - TrainResNet18
    inputs:
      repo: TrainResNet18.outputs.repo
      json: TrainResNet18.outputs.json
    resources:
      instance-type: C4
context:
  event:
    github:
      url: https://github.com/joshua-paperspace/ResNet-PyTorch