'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  UploadResNet18:
    needs:
      - CloneRepo
    uses: create-model@v1
    with:
      name: resnet18
      type: Custom
    inputs:
      model:
        type: dataset
        with:
          ref: dsrsgtp083suuyu
    outputs:
      model-id:
        type: string
    resources:
      instance-type: C4
  TestResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        ls /inputs
        echo a
        ls /inputs/model-id
        echo b
    needs:
      - CloneRepo
      - UploadResNet18
    inputs:
      model-id: UploadResNet18.outputs.model-id
      repo: CloneRepo.outputs.repo
    outputs:
      json:
        type: volume
      repo:
        type: volume
    resources:
      instance-type: C4
context:
  event:
    github:
      url: https://github.com/joshua-paperspace/ResNet-PyTorch