'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  TrainResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        cp -R ./hello.json /outputs
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      hello:
        type: volume
      repo:
        type: volume
    resources:
      instance-type: P4000
  TestResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        ls /inputs
    needs:
      - TrainResNet18
    inputs:
      repo: TrainResNet18.outputs.repo
      path: TrainResNet18.outputs.hello
    resources:
      instance-type: P4000
context:
  event:
    github:
      url: https://github.com/joshua-paperspace/ResNet-PyTorch