'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  TrainResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        ls /inputs
        echo hi
        ls /inputs/cifar10-data
        echo hi
        ls /inputs/cifar10-data/cifar-10-batches-py
        echo hi
        ls /inputs/repo
        echo hi
        echo hi
        echo hi
        cp -R /inputs/repo /outputs
        cp -R /inputs/cifar10 /outputs
        cp -R models/resnet18-epochs-5.pth /outputs
        echo hi
        echo Trained ResNet18
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      cifar10: 
          type: dataset
          with:
              ref: dsrzkbpudtxoz5q
    outputs:
      trained-model:
        type: dataset
        with:
          ref: gradient-next/resnet18-epochs-5
      cifar10:
        type: dataset
        with:
          ref: dsrzkbpudtxoz5q
      repo:
        type: volume
    resources:
      instance-type: P4000
  TrainResNet19:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        ls /inputs
        echo hi
        ls /inputs/cifar10-data
        echo hi
        ls /inputs/cifar10-data/cifar-10-batches-py
        echo hi
        ls /inputs/repo
        echo hi
        echo hi
        echo hi
        echo hi
        echo hi
        echo Trained ResNet18
    needs:
      - TrainResNet18
    inputs:
      cifar10: 
          type: dataset
          with:
              ref: dsrzkbpudtxoz5q
      repo: TrainResNet18.outputs.repo
    resources:
      instance-type: P4000
  UploadModel:
    inputs:
      model:
        type: dataset
        with:
          ref: gradient-next/ResNet-PyTorch
    outputs:
      model-id:
        type: string
    uses: create-model@v1
    with:
      name: resnet18-epochs-5
      type: Custom
context:
  event:
    github:
      url: https://github.com/joshua-paperspace/ResNet-PyTorch

