'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C4
  TrainResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        python train_model.py --layers=18 --epochs=1 2>/outputs/path
        cp -R /inputs/repo /outputs
        cp -R /inputs/cifar10 /outputs
        cp -R model /outputs
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      cifar10-data: 
        type: dataset
        with:
          ref: dsrzkbpudtxoz5q
    outputs:
      model:
        type: dataset
        with:
          ref: dsrsgtp083suuyu
      repo:
        type: volume
      path:
        type: string
    resources:
      instance-type: P4000
  TestResNet18:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        ls /inputs
        echo hi
        ls /inputs/model
        cp -R /inputs/repo /outputs  
        python test_model.py -m /inputs/model/resnet18-epochs-1.pth
        cp -R test-results /outputs
    needs:
      - TrainResNet18
    inputs:
      repo: TrainResNet18.outputs.repo
      path: TrainResNet18.outputs.path
      model: TrainResNet18.outputs.model
      cifar10-data: 
        type: dataset
        with:
          ref: dsrzkbpudtxoz5q
    outputs:
      test-results:
        type: dataset
        with:
          ref: dstdrdgk1bxsbjs
      repo:
        type: volume
    resources:
      instance-type: P4000
  TrainResNet34:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        python train_model.py --layers=34 --epochs=1 2>/outputs/path
        cp -R /inputs/repo /outputs
        cp -R /inputs/cifar10 /outputs
        cp -R model /outputs
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      cifar10-data: 
        type: dataset
        with:
          ref: dsrzkbpudtxoz5q
    outputs:
      model:
        type: dataset
        with:
          ref: dsrlhp90qjun0k8
      repo:
        type: volume
      path:
        type: string
    resources:
      instance-type: P4000
  TestResNet34:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        ls /inputs
        echo hi
        ls /inputs/model
        cp -R /inputs/repo /outputs  
        python test_model.py -m /inputs/model/resnet34-epochs-1.pth
        cp -R test-results /outputs  
    needs:
      - TrainResNet34
    inputs:
      repo: TrainResNet34.outputs.repo
      path: TrainResNet34.outputs.path
      model: TrainResNet34.outputs.model
      cifar10-data: 
        type: dataset
        with:
          ref: dsrzkbpudtxoz5q
    outputs:
      test-results:
        type: dataset
        with:
          ref: dstdrdgk1bxsbjs
      repo:
        type: volume
    resources:
      instance-type: P4000
  CompareModels:
    uses: script@v1
    with:
      image: nvcr.io/nvidia/pytorch:21.10-py3
      script: |-
        cd /inputs/repo/
        python print_test_results.py
        ls
    needs:
      - TestResNet18
      - TestResNet34
    inputs:
      repo: TestResNet18.outputs.repo
      test-results-a: TestResNet18.outputs.test-results
      test-results-b: TestResNet34.outputs.test-results
    outputs:
      bestmodel:
          type: string
    resources:
      instance-type: P5000
  UploadModel:
    inputs:
      model:
        type: dataset
        with:
          ref: CompareModels.output.bestmodel
    outputs:
      model-id:
        type: string
    needs:
      - CompareModels
    uses: create-model@v1
    with:
      name: resnet-model
      type: Customer 
context:
  event:
    github:
      url: https://github.com/joshua-paperspace/ResNet-PyTorch
